### ISSUE TITLE
Incorrect Setup instructions

### ISSUE THREAD

**Issue by androidacy-user** [Melvin-Abraham/gaudc-wiki#1]
Two things I noticed:

1) The auth handler needs to be `http` not `https` or chrome shows an SSL error.
2) The client type **MUST** be desktop, not web, or personal results **CANNOT** be enabled.

**Comment by Melvin-Abraham** [comment]
The first issue would be addressed as this solution seems to be working for many. For the second one though, the switch to web client was made in response to [this issue](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/671) which occurred due to some changes from Google's side.

**Comment by Melvin-Abraham** [comment]
This issue has been addressed and an FAQ section for the same has been added. Refer [FAQ: Why am I getting SSL Protocol Error when assistant opens localhost?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-am-i-getting-ssl-protocol-error-when-assistant-opens-localhost)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
